# Generated by Django 6.1 on 2026-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.FloatField()),
                ('motif', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE_CHEF', 'En attente Chef de Service'), ('REFUSEE_CHEF', 'Refusée par le Chef'), ('EN_ATTENTE_SANTE', 'En attente avis Conseil de Santé'), ('EN_ATTENTE_RH', 'En attente Administration RH'), ('REFUSEE_RH', 'Refusée par RH'), ('VALIDEE', 'Validée définitivement')], default='EN_ATTENTE_CHEF', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_validateur', models.CharField(max_length=30)),
                ('decision', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('droits_acquis', models.FloatField(default=22.0)),
                ('jours_reportes', models.FloatField(default=0.0)),
                ('jours_consommes', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duree_max_jours', models.PositiveIntegerField(default=22)),
                ('necessite_piece_jointe', models.BooleanField(default=False)),
            ],
        ),
    ]
