# Generated by Django 6.1 on 2026-08-13 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapevalidation',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='conges.demandeconge'),
        ),
        migrations.AddField(
            model_name='etapevalidation',
            name='validateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soldeconge',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conges.typeconge'),
        ),
        migrations.AlterUniqueTogether(
            name='soldeconge',
            unique_together={('utilisateur', 'annee')},
        ),
    ]
