# Generated by Django 5.2.12 on 2026-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_alter_demandeconge_id_alter_etapevalidation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jourferie',
            name='est_recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
