# Generated by Django 5.2.12 on 2026-09-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_jourferie_est_recurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeconge',
            old_name='duree_max_jours',
            new_name='duree_max',
        ),
        migrations.RenameField(
            model_name='typeconge',
            old_name='necessite_piece_jointe',
            new_name='justificatif_requis',
        ),
        migrations.AddField(
            model_name='typeconge',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
