# Generated by Django 5.2.12 on 2026-09-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0005_rename_duree_max_jours_typeconge_duree_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeconge',
            name='type_justificatif',
            field=models.CharField(blank=True, help_text='Ex: Certificat médical, Acte de naissance, Acte de mariage...', max_length=200, null=True),
        ),
    ]
