# Generated by Django 5.2.12 on 2026-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0006_typeconge_type_justificatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_CHEF', 'En attente Chef de Service'), ('REFUSEE_CHEF', 'Refusée par le Chef'), ('EN_ATTENTE_SANTE', 'En attente avis Conseil de Santé'), ('EN_ATTENTE_RH', 'En attente Administration RH'), ('REFUSEE_RH', 'Refusée par RH'), ('VALIDEE', 'Validée définitivement'), ('ANNULEE', "Annulée par l'employé")], default='EN_ATTENTE_CHEF', max_length=30),
        ),
    ]
