# Generated by Django 5.2.12 on 2026-09-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_bureau_service_alter_division_id_and_more'),
        ('users', '0003_remove_utilisateur_bureau_utilisateur_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bureau',
        ),
    ]
