# Generated by Django 6.1 on 2026-09-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('CHEF_SERVICE', 'Chef de Service'), ('RH', 'Ressources Humaines'), ('ADMIN', 'Administrateur Système')], default='EMPLOYE', max_length=20),
        ),
    ]
