# Generated by Django 5.2.12 on 2026-09-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_bureau_service_alter_division_id_and_more'),
        ('users', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='bureau',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organisation.service'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
