# Generated by Django 5.2.12 on 2026-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_utilisateur_bureau_utilisateur_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
